# 1. KONFIGURASI SERVER
server.port=8080
spring.application.name=mini-banking-api

# 2. KONFIGURASI DATABASE (PostgreSQL)

# 3. KONFIGURASI JPA & HIBERNATE

# Log SQL

# 4. KONFIGURASI CUSTOM UNTUK JWT (Tambahan Sendiri)
jwt.secret=MiniBankingApiSecretKeyYangSangatPanjangDanAmanSekali123456
jwt.expiration-ms=86400000

# 5. KONFIGURASI SPRINGDOC OPENAPI (Swagger UI)