# 1. KONFIGURASI SERVER
server.port=8080
spring.application.name=mini-banking-api

# 2. KONFIGURASI DATABASE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5430/mini_banking_api
spring.datasource.username=rizalamarulloh
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. KONFIGURASI JPA & HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Log SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# 4. KONFIGURASI CUSTOM UNTUK JWT (Tambahan Sendiri)
jwt.secret=MiniBankingApiSecretKeyYangSangatPanjangDanAmanSekali123456
jwt.expiration-ms=86400000

# 5. KONFIGURASI SPRINGDOC OPENAPI (Swagger UI)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html